"""
Post-verification Python artefact.

When NuSMV reports every spec as true, this module writes a small text file that documents
the network for the thesis. For ``simple_boolean`` mode it additionally emits a runnable
Python script that replays the discrete threshold dynamics.

For ``lif`` mode no faithful Python replay is provided — the NuSMV ``MODULE lif_*`` definition
is the authoritative semantics.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any, Dict, List, Optional

from snn_mc.ir import NetworkIR
from snn_mc.smv.prepare import SmvPrepared, or_of_sources


def write_simple_boolean_executable(ir: NetworkIR, out_py: Path) -> None:
    """
    INPUT: logical NetworkIR (DSL names) + output path for a ``.py`` file.
    OUTPUT: writes a standalone Python script simulating ``bool_thr`` semantics:
            ``next_active = (sum (src ? w : 0)) >= tau``.
    """
    edges: List[Dict[str, Any]] = [
        {"src": e.src, "dst": e.dst, "w": e.weight} for e in ir.edges if e.dst in ir.neurons
    ]
    neurons = sorted(ir.neurons)
    inputs = sorted(ir.inputs)
    consts = {k: bool(v) for k, v in ir.consts.items()}
    taus: Dict[str, int] = {}
    for n in neurons:
        pset = ir.neuron_params.get(n, "default")
        spec = ir.params.get(pset) or ir.params.get("default")
        if spec is None:
            raise ValueError(f"sim.stub: missing ParamSpec for neuron {n!r} (param set {pset!r})")
        taus[n] = spec.tau
    schedules = {k: list(v) for k, v in ir.schedules.items()}

    data = textwrap.dedent(
        f'''
        # AUTO-GENERATED by snn_mc.sim.stub — discrete-threshold neuron simulation.
        # Matches NuSMV ``bool_thr``: next(spike) := (sum (src ? w : 0)) >= tau.
        # LIF dynamics are NOT reproduced here.

        EDGES = {json.dumps(edges)}
        NEURONS = {json.dumps(neurons)}
        INPUTS = {json.dumps(inputs)}
        CONSTS = {json.dumps(consts)}
        TAUS = {json.dumps(taus)}
        SCHEDULES = {json.dumps(schedules)}
        STEPS = 21

        import random


        def src_value(src, inp_state, neu_state):
            if src in CONSTS:
                return CONSTS[src]
            if src in INPUTS:
                return inp_state[src]
            return neu_state[src]


        def net_to(dst, inp_state, neu_state):
            total = 0
            for e in EDGES:
                if e["dst"] != dst:
                    continue
                total += e["w"] if src_value(e["src"], inp_state, neu_state) else 0
            return total


        def main():
            rng = random.Random(0)
            neu = {{n: False for n in NEURONS}}
            print("t", "inputs", "neurons")
            for t in range(STEPS):
                inp = {{}}
                for i in INPUTS:
                    if i in SCHEDULES and t < len(SCHEDULES[i]):
                        inp[i] = bool(SCHEDULES[i][t])
                    else:
                        inp[i] = bool(rng.getrandbits(1))
                nxt = {{}}
                for n in NEURONS:
                    nxt[n] = net_to(n, inp, neu) >= TAUS[n]
                print(t, inp, neu)
                neu = nxt


        if __name__ == "__main__":
            main()
        '''
    ).lstrip()
    out_py.write_text(data, encoding="utf-8")


def run_simulation_stub(
    ir: NetworkIR,
    out: Path | None = None,
    *,
    prepared: Optional[SmvPrepared] = None,
    emit_mode: str = "lif",
    boolean_sim_py: Path | None = None,
) -> str:
    """
    INPUT: NetworkIR, optional output path, optional SmvPrepared, emit_mode label.
    OUTPUT: returns the stub text. If ``out`` is set, also writes it to disk.
            If ``boolean_sim_py`` is set and ``emit_mode == 'simple_boolean'``,
            additionally writes a runnable ``.py`` simulator.
    """
    from snn_mc.smv.prepare import prepare_ir as _prepare

    prep = prepared if prepared is not None else _prepare(ir)
    lines = [
        "# snn_mc.sim.stub — post-NuSMV summary (all specifications true).",
        f"# emit_mode: {emit_mode}",
        f"# neurons: {sorted(ir.neurons)}",
        f"# inputs:  {sorted(ir.inputs)}",
        f"# edges:   {len(ir.edges)}",
        "#",
    ]
    if emit_mode == "lif":
        lines.append(
            "# NOTE: LIF membrane / leak dynamics are NOT replayed here; NuSMV lif_* is authoritative."
        )
    lines.extend(
        [
            "# LIF wiring uses Boolean OR into x_exc / x_inh (sanitized names below).",
            "# simple_boolean uses per-edge weighted sum ((src) ? w : 0) + ... vs tau.",
        ]
    )

    for n in prep.neuron_list:
        xe = or_of_sources(list(prep.exc_srcs[n]))
        xi = or_of_sources(list(prep.inh_srcs[n]))
        lines.append(f"#   {n}:  x_exc := {xe} ; x_inh := {xi}")
    text = "\n".join(lines) + "\n"
    if out is not None:
        out.write_text(text, encoding="utf-8")
    if boolean_sim_py is not None and emit_mode == "simple_boolean":
        write_simple_boolean_executable(ir, boolean_sim_py)
    return text
