"""
NuSMV ``MODULE main`` emitter.

INPUT:  NetworkIR (for metadata comments) + SmvPrepared (for wiring).
OUTPUT: NuSMV source text:
        - ``emit_model_core`` -> MODULE main + VAR + DEFINE (tie aliases) + ASSIGN clauses,
                                 without CTLSPEC/LTLSPEC and without the trailing neuron MODULEs.
        - ``emit_model_smv``  -> standalone ``model.smv`` body (core + neuron MODULE tail).

Supports two neuron encodings:
    emit_mode == "lif"            — every neuron instantiates MODULE lif_<paramSet>(net_exc, net_inh, t),
                                    where net_exc/net_inh are weighted sums of the incoming edges.
    emit_mode == "simple_boolean" — every neuron instantiates MODULE bool_thr(inp_net, thr, t).
"""

from __future__ import annotations

from typing import List, Set

from snn_mc.ir import NetworkIR
from snn_mc.smv.lif_module import (
    emit_bool_thr_module,
    generate_lif_module,
    validate_params,
)
from snn_mc.smv.prepare import SmvPrepared


def _src_bool(prepared: SmvPrepared, src: str) -> str:
    """Boolean NuSMV expression that is TRUE when ``src`` is active this step."""
    if src in prepared.inputs:
        return src
    if src in prepared.consts:
        return "TRUE" if prepared.consts[src] else "FALSE"
    return f"{src}.spike"


def _weighted_sum(prepared: SmvPrepared, dst_n: str, *, sign: str = "all") -> str:
    """
    Signed sum of per-edge weights gated by Boolean sources feeding ``dst_n``.

    ``sign`` selects which edges to include:
      - ``"all"`` — every incoming edge (used by ``simple_boolean``),
      - ``"exc"`` — only excitatory edges (weight >= 0),
      - ``"inh"`` — only inhibitory edges (weight < 0).
    Each active source contributes its own edge weight, so heterogeneous
    ``weights=`` actually drive the membrane integration.
    """
    terms: List[str] = []
    for e in prepared.edges:
        if e.dst != dst_n:
            continue
        if sign == "exc" and e.weight < 0:
            continue
        if sign == "inh" and e.weight >= 0:
            continue
        b = _src_bool(prepared, e.src)
        terms.append(f"(({b}) ? {e.weight} : 0)")
    return " + ".join(terms) if terms else "0"


def emit_model_core(ir: NetworkIR, prepared: SmvPrepared, *, emit_mode: str = "lif") -> str:
    """
    INPUT: NetworkIR (metadata), SmvPrepared (wiring), ``emit_mode``.
    OUTPUT: NuSMV text for MODULE main only — no specs, no neuron MODULE tail.
    RAISES: ValueError on an unknown emit_mode.
    """
    if emit_mode not in ("lif", "simple_boolean"):
        raise ValueError(f"Unsupported emit_mode: {emit_mode!r} (use 'lif' or 'simple_boolean')")

    tie_s = prepared.tie_s
    neuron_list = prepared.neuron_list
    input_list = prepared.var_inputs
    schedules = prepared.schedules
    neuron_params = prepared.neuron_params
    renames = prepared.renames

    def root_inp(x: str) -> str:
        seen: Set[str] = set()
        cur = x
        while cur in tie_s:
            if cur in seen:
                raise RuntimeError("tie cycle slipped through validation")
            seen.add(cur)
            cur = tie_s[cur]
        return cur

    lines: List[str] = []
    h = ir.horizon
    lines.append("-- Generated by snn_mc.smv.model (model core; specs in smv.properties)")
    lines.append(f"-- emit_mode: {emit_mode}")
    lines.append(
        "-- Global clock 't' is the discrete simulation step (0..horizon), NOT threshold tau "
        "and NOT BMC depth. Schedule TRUE/FALSE on inputs applies at each t."
    )
    lines.append(f"-- horizon (simulation length): {h}")
    if ir.input_ties:
        lines.append(
            "-- Input ties (DEFINE): "
            + ", ".join(f"{s}->{ir.input_ties[s]}" for s in sorted(ir.input_ties.keys()))
        )
    if prepared.neuron_roles:
        lines.append(
            "-- Neuron roles: "
            + ", ".join(f"{n}={r}" for n, r in sorted(prepared.neuron_roles.items()))
        )
    if renames:
        lines.append(
            "-- Renamed identifiers (NuSMV-safe): "
            + ", ".join(f"{k}->{v}" for k, v in sorted(renames.items()))
        )
    lines.append("MODULE main")
    lines.append("VAR")
    # Global discrete clock shared by all neurons. Upper bound keeps the state space finite.
    lines.append(f"  t : 0..{h};")
    for i in input_list:
        lines.append(f"  {i} : boolean;")

    if emit_mode == "lif":
        for n in neuron_list:
            net_exc = _weighted_sum(prepared, n, sign="exc")
            net_inh = _weighted_sum(prepared, n, sign="inh")
            pset = neuron_params.get(n, "default")
            lines.append(f"  {n} : lif_{pset}({net_exc}, {net_inh}, t);")
    else:
        for n in neuron_list:
            net_ex = _weighted_sum(prepared, n, sign="all")
            pset = neuron_params.get(n, "default")
            thr = prepared.param_specs[pset].tau
            lines.append(f"  {n} : bool_thr({net_ex}, {thr}, t);")

    if tie_s:
        lines.append("DEFINE")
        for slave in sorted(tie_s.keys()):
            lines.append(f"  {slave} := {root_inp(slave)};")

    lines.append("")
    lines.append("ASSIGN")
    lines.append("  init(t) := 0;")
    lines.append(f"  next(t) := (t < {h}) ? (t + 1) : {h};")
    for i in input_list:
        if i in schedules and schedules[i]:
            lines.append(f"  next({i}) :=")
            lines.append("    case")
            for idx, val in enumerate(schedules[i]):
                v = "TRUE" if val else "FALSE"
                lines.append(f"      t = {idx} : {v};")
            lines.append("      TRUE  : {TRUE, FALSE};")
            lines.append("    esac;")
        else:
            lines.append(f"  next({i}) := {{TRUE, FALSE}};")

    return "\n".join(lines) + "\n"


def emit_lif_modules(prepared: SmvPrepared) -> str:
    """
    INPUT: SmvPrepared (uses ``neuron_params`` to discover which parameter sets are referenced).
    OUTPUT: text containing one ``MODULE lif_<name>`` definition per referenced parameter set.
    """
    lines: List[str] = []
    used_paramsets = sorted({prepared.neuron_params.get(n, "default") for n in prepared.neuron_list})
    for pset_name in used_paramsets:
        spec = prepared.param_specs[pset_name]
        validate_params(spec)
        lines.extend(generate_lif_module(spec))
    return "\n".join(lines) + ("\n" if lines else "")


def emit_model_smv(ir: NetworkIR, prepared: SmvPrepared, *, emit_mode: str = "lif") -> str:
    """
    INPUT: NetworkIR + SmvPrepared + emit_mode.
    OUTPUT: standalone ``model.smv`` body (no temporal specs).
    """
    tail = emit_lif_modules(prepared) if emit_mode == "lif" else emit_bool_thr_module()
    return emit_model_core(ir, prepared, emit_mode=emit_mode) + tail
